version: "3.8"

services:
  sqte-website:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
